<?php
DEFINE('DB_HOST','localhost');
DEFINE('DB_USER','');   //COMPLETAR CON EL USUARIO
DEFINE('DB_PASSWD',''); //COMPLETAR CON LA CONTRASEÑA
DEFINE('DB_DATABASE',''); //COMPLETAR CON EL NOMBRE DE LA BASE DE DATOS
?>
